{% set name = "IS2view" %}
{% set version = "0.1.1" %}
{% set sha256 = "ec79b4c96d2b8277f76ef85cb48beb858b053da3b619696919e4d093a7fc0874" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
    - setuptools
  run:
    - dask
    - h5netcdf
    - ipyleaflet
    - matplotlib-base
    - numpy
    - python >={{ python_min }}
    - rioxarray
    - setuptools-scm
    - setuptools
    - xarray

test:
  imports:
    - IS2view
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tsutterley/IS2view
  summary: |
    Interactive visualization and data extraction tool for the ICESat-2 ATL14/15 Gridded Land Ice Height Products
  license: MIT
  license_file:
    - LICENSE
  doc_url: https://is2view.readthedocs.io
  dev_url: https://github.com/tsutterley/IS2view

extra:
  recipe-maintainers:
    - tsutterley
