{% set name = "IS2view" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 58f3f610b546984e12884d87a53c25ca2316962adeb34146621334843cd22b28

build:
  number: 0
  noarch: python
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-scm
    - setuptools
  run:
    - python >=3.6
    - dask
    - h5netcdf
    - ipyleaflet
    - matplotlib-base
    - numpy
    - rioxarray
    - setuptools-scm
    - setuptools
    - xarray

test:
  imports:
    - IS2view
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tsutterley/IS2view
  summary: |
    Interactive visualization and data extraction tool for the ICESat-2 ATL14/15 Gridded Land Ice Height Products
  license: MIT
  license_file:
    - LICENSE
  doc_url: https://is2view.readthedocs.io
  dev_url: https://github.com/tsutterley/IS2view

extra:
  recipe-maintainers:
    - tsutterley
